### ISSUE TITLE
additional fields

### ISSUE THREAD

**Issue by dws122** [bizbudding/wampum-forms#10]
What's the likelihood of adding additional fields during data entry?
zipcode
phone number
company

**Comment by JiveDig** [comment]
We have to way out the benefit of specific use-cases like that vs just using a gravity form. I could add those field types, or figure out some hook/filter when building the form and saving the data to add custom fields.  Just not sure how often it would be needed vs the time to build/maintain.

**Comment by dws122** [comment]
General consensus is to redirect the Wampum Form to another form (ie Gravity Form) for additional data collection.
